### ISSUE TITLE
Make sure there are no references to HTTP in the solution

### ISSUE THREAD

**Issue by klarose** [capport-wg/architecture#11]
As pointed out on the mailing list, there's a few places we refer to an HTTP API. Make sure we don't do that.

>    This document aims to document consensus on the CAPPORT architecture.
>   DHCP or Router Advertisements, an optional signaling protocol, and an
>  HTTP API are used to provide the solution.  The role of Provisioning
> Domains (PvDs) is described.

**Comment by martinthomson** [comment]
It's OK to talk about HTTP when talking about the semantics of the protocol.  You only need to make it clear that HTTP over TCP (without TLS) is not permitted.

**Comment by liucougar** [comment]
we have the current text:

> The API MUST use TLS for privacy and server authentication.
> The implementation of the API MUST ensure both privacy and integrity of
> any information provided by or required by it.

...

> The solution described here assumes that when the User Equipment needs to
> trust the API server, server authentication will be performed using TLS
> mechanisms.

...

> The solution described here requires that the API be secured using TLS.
> This is required to allow the user equipment and API Server to exchange
> secrets which can be used to validate future interactions. The API must
> ensure the integrity of this information, as well as its confidentiality.

what else shall we add please? or shall we explicitly say HTTPS (besides TLS)?

**Comment by martinthomson** [comment]
This might have been overtaken by events.  I don't see anything in the current doc that seems problematic.
