### ISSUE TITLE
Describe what happens if the portal URI changes

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/architecture#15]
Probably not a lot, except that future requests might go there.  Because we don't hold any state for these resources, that's probably OK.

**Comment by martinthomson** [comment]
@liutiger do you think that you could take a swing at this?

**Comment by liucougar** [comment]
By portal URI, you meant the URL to the json file?

If so, it seems the ways how it could be changed are:
In the case of DHCPv4/v6,in a renewal/rebind of DHCPv4/v6 lease, the end user equipment could receive a new portal URI in the DHCP renew/rebind response.
In the case of RA, the end user device may receive a new portal URI in a new RA message. (In RA case, is it possible that there are multiple RA servers sending out different portal URI?)

Is there any other possibilities?

Do I understand correctly that you are suggesting add something like the following?
If a new Portal URI is provided via DHCPv4/v6 renew/rebind or RA, use the new one.

Where shall we add this section please? a new paragraph under 2.2.1.  DHCP or Router Advertisements? or a new sub section 4.3 under 4 Solution Workflow?

**Comment by martinthomson** [comment]
Right.  I forget whether this was about the API URL (the JSON) or the user portal URL.  In either case, they can change and I think that's OK.

The RA case is interesting in the sense that it might imply a different router advertising different coordinates, as you say, but if it is the same router, then that should be regarded as a change.

This came up in discussion and some people felt that it needed to be acknowledged.  Your suggested outcome is probably the only sensible one: if you need to contact the API, use the most recent value you have.

As for location in the document, a new Section 4.x describing how updated details can be acquired seems right.

**Comment by liucougar** [comment]
Fixed in #30
