### ISSUE TITLE
Deprecate or update RFC7710?

### ISSUE THREAD

**Issue by dcdolson** [capport-wg/architecture#2]
RFC7710 is unclear on what kind of API is to be found at the URI conveyed in the DHCP option.
This could be clarified, OR deprecated if replaced by PvD.

**Comment by ekline** [comment]
I think the room temperature in Singapore was that 7710 URIs would still be available for us to use as the API endpoint.  We just need to update 7710 when publish.

**Comment by martinthomson** [comment]
@wkumari seemed to be OK with us doing an update/revision if we needed to.

**Comment by klarose** [comment]
The most recent discussions regarding the API also seem to be trending towards using RFC7710 to discover at least one URI. So, I think we definitely need to keep it. The question is now: do we need to update it? I think that answer will be resolved in the API discussions we're having now.

**Comment by ekline** [comment]
Yes, the outcome from London was to rev the document.  Warrren and I are working up a 7710bis.

**Comment by klarose** [comment]
Answer provided: we are updating it. Thanks, @ekline.
