### ISSUE TITLE
DoH, split horizon, and captive portals

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/architecture#25]
In the case that access to an external DNS resolver is permitted, this could complicate the process of contacting the API server.  A recommendation to disable that might be wise.

(I only included the DoH thing in the title because everyone needs a DoH issue, but this is not really one of those.)

**Comment by klarose** [comment]
Do we have an example of how it complicates things? It may help to set the context. I'm guessing it's because the API may not be globally addressable/doesn't have an external DNS entry?

**Comment by martinthomson** [comment]
Two modes of failure:

1. Local resolvers might be the only ones that produce an answer that is usable for devices in the network. (This is confirming your guess.)

2. Remote resolvers might be blocked.

**Comment by martinthomson** [comment]
Discussed in Montreal:
General agreement to use the local resolver for the purposes of contacting the captive portal (API, and other pages that stem from that).  The implementation complexities that arise are non-trivial, but we need to at least acknowledge what the right thing to do is.

**Comment by martinthomson** [comment]
Also discussed in Singapore and the general view there was that while UE should avoid using an external resolver, we should also recommend that networks not rely on split horizon in order to work.  If the portal API is accessed from outside of the network, it would be better if it worked.  That wasn't a firm requirement, but merely a recognition of the fact that the UE might not always pick the right network path for sending requests (whether they are DNS or HTTP matters little here).

**Comment by liucougar** [comment]
Given #28, is there anything else we want to add for this issue please?

**Comment by martinthomson** [comment]
I think that #28 is a good approach for addressing this.

**Comment by klarose** [comment]
So, it sounds like we're finished with this, then?

**Comment by martinthomson** [comment]
Yessir.
