### ISSUE TITLE
URLs should be context-free

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/architecture#28]
Based on discussion in Singapore, the group decided to recommend (not require) that URLs use names that can be resolved from the public DNS (no split horizon, etc...).  The content served from those URLs should also not be dependent on the network path, but instead the URL would include all information necessary to produce the resource.

**Comment by liucougar** [comment]
i remember we were talking about primarily venue URL should be context free

however, the architecture doc does not mention the venue URL (only portal URL)

which section shall we add this context-free please? (maybe in section_pvd?)

shall we also mention this in the api doc?

**Comment by martinthomson** [comment]
I think that @tfpauly might want to think about what to include once we have text here.

The text can be generic.  I would suggest a new Section 3.5 as this relates to identification of UE.  That is, you say that information presented in the API - and in particular URLs - need to include identification UE information.  In particular, any information that is used from this context should not depend on ambient information, such as the remote address on a connection, as this information might be used by the UE on a different network interface.  For example, a user might access venue information URLs from another network.

You might also then mention that this might expose the service to spoofing or replay of that information in those cases.  This might mean that though the URL might "work", it might not present all options.  For instance, payment options might not be offered, or if they are, warnings might be shown that the payment is not for the current connection.
