### ISSUE TITLE
Clarify Provisioning Domains capport representation

### ISSUE THREAD

**Issue by dcdolson** [capport-wg/architecture#3]
Does PvD mechanism deliver the capport state, or a pointer to the capport API, from which capport state is retrieved?

**Comment by dcdolson** [comment]
In IETF101 capport meeting, I think I heard that PvD is not designed for conveying per-UE state. Hence, PvD may provide a URI to the capport API, but not convey the state itself.

**Comment by martinthomson** [comment]
@klarose, is this addressed in #20 in the sense that the referenced doc covers it?

**Comment by klarose** [comment]
Yes. I think it is.
