### ISSUE TITLE
Name of the API

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/architecture#31]
This is a little inconsistent.  I see "CAPPORT API" and "Captive Portal API", but mostly just "API" or "API server".

Having a short form (API) seems useful.  The longer form probably needs to be "Captive Portal API" to avoid having to define what "CAPPORT" means.  There seems to be value in distinguishing between the API and the entity that provides it, so maybe the latter distinction is fine to leave alone.

**Comment by klarose** [comment]
So "API" as short for "Captive Portal API" and "API server" as short for "Captive Portal API server"?

Seems reasonable.

**Comment by klarose** [comment]
Fixed in #33

**Comment by klarose** [comment]
Fixed in #33
