### ISSUE TITLE
Mechanism to indicate "no captive portal"

### ISSUE THREAD

**Issue by dcdolson** [capport-wg/architecture#4]
The current (RFC7710) DHCP option doesn’t have a way to say “there’s no captive portal to talk to”, so whenever we don’t see it, we’ll need to send a probe.
Giving a network a means of indicating there is no capport would improve connecting time.
Same for Provisioning Domains info.

**Comment by ekline** [comment]
Could we have something like "urn:capport:unrestricted" as a positive signal (as opposed to no option or empty strings either of which might be configuration errors)?

**Comment by klarose** [comment]
@ekline That's an interesting idea. It's fairly simple, though it wouldn't work with any legacy implementations of RFC7710 (if there even are any...)

Would this necessitate an update to the draft? It says that the URI is something the user should connect to. If we give them something that won't accept a connection, is that bad?

**Comment by ekline** [comment]
I think (a) there are likely no significant existing implementations of RFC 7710, neither on the server side nor the client side, and (b) this is a perfectly good bullet point question to ask the group in London if you don't add it to the document or confirm with the group if you do.

**Comment by dcdolson** [comment]
@klarose Trying to connect to something that won't accept a connection is, in my opinion, undesirable.
It's creating an error that might be hard to distinguish from actual network problems. Also, it might take some time to resolve (e.g., how many TCP SYN retransmissions before giving up?)

**Comment by ekline** [comment]
No HTTP library should ever try to do any DNS or connection initiations for a urn: URI.  It should fail fast inside the host's code (i.e. no packets emitted).

**Comment by dcdolson** [comment]
Does it still look like an error to the application? Would code look like this?
```
if (do_request(uri) == FAIL) {
    if(uri == "urn:capport:unrestricted") {  // not an error
        return OK;
    }
    return FAIL;
}
```
If there is going to be code to check the string, it's better to not do the request.

**Comment by klarose** [comment]
What about using PvD to indicate that there's no captive portal?  Or do we think that that's a little too much overhead, given that most networks won't have one?

**Comment by klarose** [comment]
@ekline The RFC7710bis you're working on will tackle this?

**Comment by ekline** [comment]
Long overdue reply: yes.

=)

There's now even a -00 of it:

    https://datatracker.ietf.org/doc/draft-ekwk-capport-rfc7710bis/
