### ISSUE TITLE
I-D.nottingham-capport-problem is still referenced

### ISSUE THREAD

**Issue by dcdolson** [capport-wg/architecture#48]
This paragraph still exists in the document:
   Problems with captive portal implementations have been described in
   [I-D.nottingham-capport-problem].  [If that document cannot be
   published, consider putting its best parts into an appendix of this
   document.]
Maybe pull in sections 3 & 4 from https://tools.ietf.org/html/draft-nottingham-capport-problem-01 ?

**Comment by klarose** [comment]
@martinthomson I'm fine taking Dave's suggestion to pull in those sections. However, I'm not sure of the best way to attribute the content to that original document/it author. I imagine simply acknowledging Mark is sufficient, but if there is a better practice, please let me know.

**Comment by klarose** [comment]
Though I am somewhat concerned that it's a lot of text, and could be contentious if we're adding it after last call. For example statements like the one about access only being possible to steal in an insecure wireless network--I'm not convinced that's actually true. Given that this document wasn't really vetted, perhaps it'd be better to just try to summarize in the intro some of the more salient points.

**Comment by martinthomson** [comment]
Yes, if we pull in additional text, then I might feel obligated to run another last call.  We can ask Mark for permission (not at-mentioning here yet), but I want to understand what this document lacks that Mark's has.  My sense is that the text can be just cut, or the problem statement summarized in one of two paragraphs.

**Comment by dcdolson** [comment]
Good question. I think the nottingham problem statement was very useful for thinking about the problem and what to avoid. But we do have the guiding principles in the introduction.
It would certainly be easier to just drop the mention of it, and focus on what should be vs. what should not be.
