### ISSUE TITLE
Which portion of packet is used for capport enforcement?

### ISSUE THREAD

**Issue by dcdolson** [capport-wg/architecture#5]
E.g., MAC address or IP address? Or?
Use of MAC address means enforcement must be on the local layer2 segment.
Use of IP address has complexity around the user device randomly changing the IPv6 address.

**Comment by ekline** [comment]
In addition to MAC address it could also be done based on other "link properties" like DSL Line ID.

**Comment by klarose** [comment]
I would like to come up with something generic if possible. What are the properties of the information we're using that are desirable?
* Uniquely identifies the host trying to connect at a given time
* Hard to spoof
* Visible/understood by the API for correlation
* ...

Whether or not these apply to a given piece of information depends a lot on where the devices are in the network. For example, if the captive portal enforcement *and* API are being applied at a location where the DSL Line ID is known, then using that is sufficient. I'd be sad if we restricted compliant implementations from doing so.

However, if the API were elsewhere in the network, the line ID likely would not be sufficient. So, we again need to allow other options.

So, it seems like we need to:

1.  Recommend a set of properties
2.  Describe how to evaluate whether they apply to a given type of information
3.  Describe how to tie break if a number of pieces of information satisfy the properties.

**Comment by martinthomson** [comment]
It sounds like you are on the right track here.  (The tie break probably isn't necessary as long as you have agreement between the entities that consume/exchange the information,)

I think that we should expound upon the hard to spoof part more.  The degree of removal from the UE is likely to mean that there are boxes between UE and enforcement/API.  More network hops means that each intermediate node needs to preserve the integrity of the identifier.  For instance, if the network used source IP address, then any intermediate router would have to ensure that the IP address were not spoofed.

That means, for instance, knowing that this line ID is assigned a particular IP address and not allowing packets that claim other source IP addresses to pass.  Or, at the next hop, either trusting that the router that forwards the packet has done these checks, and maybe adding extra verification (such as that the IP address comes from the subnet assigned to that router).

**Comment by martinthomson** [comment]
Offline, Erik mentioned another option, which is doing what DHCP does and have a trusted agent on the same link (a relay).  For HTTP, redirects and gatewaying are options that preserve visibility of the identification information without requiring lots of effort.

**Comment by ekline** [comment]
I think the write up of key properties a good idea.  I have been thinking of them as "link attributes" where the enforcement point can take action on them (e.g DSL line-id, MAC address, or IPv6 prefix is the network architecture is known to the enforcement point).

Focusing on the requirements for the source of the identifier and its authenticity is obviously integral.

And yes: +1 to giving some concrete examples of how implementation might do this, specifically we should include MAC address and DSL line-id at a minimum.  It's quite likely this section will be valuable for referencing by implementors and requirements docs.

**Comment by ekline** [comment]
The relay/gateway idea is basically this:

    (a) take as given that the enforcement point must make its decision on some link or network architecture attribute(s) and must be situated at a point where this/these can be observed and acted upon

   (b) observe that (a) means the enforcement is essentially the best source of authenticity for this information (pulling out MAC addresses or whatnot)

    (c) note that enforcement points today already do HTTP rewriting, and that it probably would not be onerous for them to actually be the first API endpoint the client talks to, even over HTTPS

    (d) it can then issue the client a redirect with some identifying information and any authentication tokens required to any off-net API server if the API server is actually not also located within the enforcement point.

Does that make sense?

**Comment by martinthomson** [comment]
(Edit FTW)

Also, we need to point out that if a redirect is used, then the information will transit the UE and therefore needs integrity protection.  This is tricky and you don't want to end up building a token binding architecture, because we have more than one of those already.  Basically, if the redirect includes information about my identity, then you need to prevent me from giving this to someone else and having them pay for my network access.  The UE needs to know that the API and portal are both able to correctly identify the UE.

Having the enforcement point act as a relay (in the DHCP relay sense) or gateway (the HTTP term) might make this more tractable.

**Comment by ekline** [comment]
Agreed. However, I would expect that presumably there is already a (set of) common authentication mechanism(s) in use today, though, right?

I mean, whenever I connect to a portal and I see &mac=00:00:5E:00:53:00:xx in the redirected URL I assume there's other bits that are, for example, hmac-signed *or* it's been deemed not important since the only thing you can /currently/ do is pay for someone else's access.

**Comment by martinthomson** [comment]
Note that an HMAC can only help if the API is able to *see* the identifier as well.  Otherwise, that `&mac=00:00...` thing is a bearer token.  The thing with bearer tokens is that whoever has it can use it.  That's not necessarily a good property.

**Comment by dcdolson** [comment]
Spoofing a source IP address doesn't give one network access (responses go to the real owner).
Spoofing allows one to mount an attack and charge it to another user.
Is this problem in scope for capport group, which I thought was more about avoiding HTTP and DNS modifications?

**Comment by martinthomson** [comment]
If an IP (or prefix thereof) is used to identify the UE, then the API will see that IP and can use it.  If, as you say, it is spoofed, then connections fail and talking to the API doesn't work.

But MAC addresses or line identifiers are different, because they aren't necessarily visible to an API.  That's where the bearer token issue arises.  If the identifier is visible to the API, then it's easy.

**Comment by dcdolson** [comment]
I was trying to suggest that using IP address is a pretty good solution. The problems with IP address might be orthogonal to the capport mandate.

**Comment by martinthomson** [comment]
I suspect that IP is pretty good, yes.  But I know that other identifiers are used, and we should include text that explains the implications of choosing other than IP.

**Comment by ekline** [comment]
Enforcing by IP Prefix, where prefixOf(IPv4 address) == /32 and prefixOf(IPv6 address) <= 64, seems likely to be simple for both enforcement and API endpoints (where separate).

We can generally depend on return routability as part of connection establishment to address spoofing.  In the futuristic case of a QUIC-enabled API endpoint it might well be possible to issue some commands within a single packet sans return routability.  At the moment the API doesn't really let you do any damage, but this is stuff we should have documented in the relevant security sections.

Lastly, my biggest remaining concern is that folks might erroneously assume that "IPv6 == 128bit IPv4", which is just not true (as we know, but some readers might not).  If we were to see deployment of enforcement points that didn't allow clients to form new IPv6 addresses on the same link and use them freely (i.e. without re-authenticating) then that could be seen as violating the spirit of RFC 7934 (and generally be bad for the IPv6 Internet).  I can already imagine the defensive code in Android to use a new IPv6 address for every captive portal API call, just to be sure.  :-/

**Comment by klarose** [comment]
Closing this for now, as we discussed at length during the last meeting, with no real conclusions beyond what's already in the document. We can always revisit with more detail or specific recommendations.
