### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/architecture#6]
It sure would be nice if we could mandate the use of HTTPS for the API.  It would be absolutely necessary if the API were used to exchange secrets.

HTTPS does make some things a lot harder.  Traps for the unwary lie in:

* OCSP or CRL validation which require that clients talk to servers that might not be on the whitelist (answer: use OCSP stapling or whitelist those names; the former being far better overall)
* non-unique names like those that use IP addresses or `.local` (possible answer: use real names)
* client clock skew that can't be corrected without contacting a blocked time server (rare but annoyingly hard to fix in practice)

**Comment by dcdolson** [comment]
It might help to clarify the reasons to use HTTPS. Privacy? Authenticating the server? Making auth scheme simpler by permitting basic user/pass method?

**Comment by adamroach** [comment]
@dcdolson -- As a practical matter, browsers are increasingly moving toward warning users about submitting information on non-https pages, [especially passwords](https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox). Starting this summer, Chrome plans to [warn about non-https pages regardless of content](https://techcrunch.com/2018/02/08/chrome-will-soon-mark-all-unencrypted-pages-as-not-secure/). In light of recent trends, it would seem ill-advised to publish a new specification that uses unsecured http.

**Comment by martinthomson** [comment]
Aside from Adam's point, which should be sufficient, the confidentiality of any secrets (the API doc has one right now), and integrity of discovery should be good reasons to add.

On integrity, anything we do is still vulnerable to the RA or DHCP producing invalid values, but at least that will be the only exposure. The operating theory is that when those are compromised, then you are connecting to whatever network the attacker chooses (as opposed to the network that the person who installed the equipment thinks of).  I don't think that people are currently especially concerned about those attacks, those who deploy the equipment are able to defend against that sort of attack fairly trivially.

**Comment by klarose** [comment]
Reading through the draft again, we have mentioned that the api MUST _support_ TLS. Is there any particular reason for HTTPS as opposed to TLS? Putting HTTPS constrains the API solutions, so I want to make sure that HTTPS vs some other application layer protocol. 

Now, I highlighted support for a reason. Are we taking issue with that wording? Saying that the API supports TLS does not mean that it must only use TLS. So, I can definitely reword it. But, I think we need some more justification to suggest HTTPS over a more general TLS.

**Comment by klarose** [comment]
I updated the wording to make TLS required. If we decide on HTTPS vs TLS, I'll make further updates accordingly.

For now I've submitted a pull request with this change.

**Comment by mcr** [comment]
I would like integrity and privacy as a MUST.   Just waving some TLS on top of it is not quite enough.
The points that Martin makes are particularly acute, and I've seen WAY TOO MANY captive portals with expired certificates, or just plain wrong names.   I would rather those portals used HTTP, and yes, failed if the browser considered it insecure.

Or to put it another way, if there is going to be an override visible to any user, I'd rather it was "I agree to submit this via HTTP" rather than "I agree to pretend I'm using HTTPS, despite having invalid time, no OCSP, and the name being wrong".

**Comment by klarose** [comment]
@mcr I have added a requirement on the API that it must provide integrity and privacy. Does that sufficiently address your concerns, or do you think we should expand a little on concerns about implementations that erroneously claim security/mislead their users? I don't want to be too verbose, but it could help to provide guidance.

**Comment by ao-8** [comment]
I agree "integrity and privacy as a MUST" for both API and portal URI(Captive Portal can use HTTPS today, right?).
Since Android 7.0, without success from the https probe they do not use a network automatically. The user needs to manually select it, so I think that HTTPS, TLS, or some way of encryption is needed for capport to improve its user experience, too.

**Comment by mcr** [comment]
Kyle Larose <notifications@github.com> wrote:
    > @mcr I have added a requirement on the API that it must provide
    > integrity and privacy. Does that sufficiently address your concerns, or
    > do you think we should expand a little on concerns about
    > implementations that erroneously claim security/mislead their users? I
    > don't want to be too verbose, but it could help to provide guidance.

I will review text....

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by klarose** [comment]
People seemed fairly happy with the results from -01.
