### ISSUE TITLE
Clarify "supports the present architecture"

### ISSUE THREAD

**Issue by dcdolson** [capport-wg/architecture#61]
A reviewer says,
```
> — Section 2.3 —
> 
>    The API SHOULD provide evidence
>    to the caller that it supports the present architecture.
> 
> I don’t understand what this means; can you explain?
```
Suggestion: state that a version of the protocol should be included in the API response.

**Comment by martinthomson** [comment]
Isn't the content-type of the API response sufficient indication?

That implies that we might need a new content-type if we want to make incompatible changes in a subsequent revision, but I think that is a good plan.

**Comment by dcdolson** [comment]
At the architecture level, can we state the point more clearly?
Maybe better to state what the User Equipment should do if the API response doesn't make sense?

**Comment by klarose** [comment]
So, the fact that we've discovered the API likely means that we're interacting with the architecture -- i.e. we got there from PvD or the dhcp option. So, I'm not sure what it would mean to not support the architecture in that case. It would be a provisioning mistake, I guess? We should suggest what the UE could do in that case, though, for robustness. So, maybe mention that the API should have a content-type in the response to indicate that it is indeed a captive portal API, and then what to do if the UE doesn't recognize that?

**Comment by martinthomson** [comment]
So I think that the reviewer here was simply confused about the choice of words and phrasing.  How about:

A caller to the API needs to be presented with evidence that the content it is receiving is for a version of the API that it supports.  For an HTTP-based interaction, such as in {{API}} this might be achieved by using a content type that is unique to the protocol.
