### ISSUE TITLE
Confusing "Evaluating an Identifier" section.

### ISSUE THREAD

**Issue by dcdolson** [capport-wg/architecture#62]
A reviewer writes,
```
> — Section 3.3 —
> Are we really talking about evaluating individual identifiers here?
> Or does this really mean to discuss *methods* of generating or
> choosing identifiers?
```
I think we should rewrite this section to be about evaluating types of identifiers or sources of identifiers.

**Comment by klarose** [comment]
Agreed. It's ambiguous as to whether we're describe how to evaluate `2001:db8::` equals `00:11:22:33:44:55`, or whether we're talking about the types (ip vs ethernet)
