### ISSUE TITLE
Is the URI mandatory?

### ISSUE THREAD

**Issue by martinthomson** [capport-wg/architecture#71]
Tirupachur Comerica, Subash writes:

> At minimum, the API MUST provide: (1) the state of captivity and (2) a URI for the Captive Portal Server.
>
> - However, in draft-ietf-capport-api, section 5: API State Structure, only "captive" (boolean): is mandatory whereas "user-portal-url" (string): is optional. One of these two drafts may need an update for consistency.

**Comment by klarose** [comment]
This was also brought up by Martin Duke during the the api document's last call. Let's fix it.

Two options were raised during that review (by Tommy and Erik, respectively):
 - Require that the API be *able* to provide the URI
 - Qualify the requirement to indicate when the URI is required (e.g. when captive portal enforcement may be active).

Some proposals:

```
At minimum, the API MUST provide the state of captivity. Further the API MUST be able to provide
a URI for the Captive Portal Server. 
```

```
At minimum, the API MUST provide the state of captivity. Further the API MUST also provide
a URI for the Captive Portal Server when captive portal enforcement may be active.
```

I'm not sure it's worth discussing the use-case that leads to it being useful for it to be optional (e.g. the venue w/ notification or extra info).

**Comment by dcdolson** [comment]
We went with the first proposal, "the API MUST be able to provide a URI"
