### ISSUE TITLE
RA used, but not defined

### ISSUE THREAD

**Issue by klarose** [capport-wg/architecture#81]
We never define what an 'RA' is, but we use that term in section 4.1.

We should consider expanding it to the full term (Router Advertisement). We may also want to add an informative reference to it when we first mention it.

Note that we have the same problem with DHCP here -- I'm not sure offhand what the best practice is regarding terms that have fairly wide use, but may not be understood by everyone (and even what that set of terms is).

**Comment by ekline** [comment]
RA is listed in the abbreviations document:

  * https://www.rfc-editor.org/materials/abbrev.expansion.txt

but of course "expand on first use" seems like sound editorial practice.
