### ISSUE TITLE
Consider mentioning that the User Portal URL be unguessable

### ISSUE THREAD

**Issue by klarose** [capport-wg/architecture#95]
> Section 3.5
>
>    Accessing the API MAY depend on contextual information.  However, the
>    URIs provided in the API SHOULD be unique to the UE and not dependent
>    on contextual information to function correctly.
>
> Should the per-UE APIs and/or the mapping between UE and per-UE API be
> unguessable?  (Do we want to reference Capability URLs
> [https://www.w3.org/TR/capability-urls/]?)
>
That's not a bad idea. Does anyone else have an opinion on this? I'm currently planning on taking the suggestion of mentioning that they should be unguessable and reference that document.

**Comment by tfpauly** [comment]
This sentence refers to URLs in the API blob, not the API itself. We definitely are okay with a common API URL or a guessable one. That’s an option.

**Comment by klarose** [comment]
> This sentence refers to URLs in the API blob, not the API itself. We definitely are okay with a common API URL or a guessable one. That’s an option.

Right. I'm not sure what I was thinking.

@tfpauly What about the URIs provided by the API itself? Do you have an opinion whether we should suggest suggest that they be unguessable?

One thought is that the API server and web portal could agree on an mechanism to cipher the UE's identifier, so that even if it's something possible guessable (i.e. the IP), and attacker couldn't spoof it.
